# 生产环境
#online: true       # 线上才验证登录
online: false       #

server:
   port: 8080
#   servlet:
#    path: /medical

logging.config: classpath:log-prod.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: bus-refresh
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
    application:
      name: medical-service
    cache:
      type: redis
    session:
      store-type: redis
    redis:
      host: 172.30.1.251
      port: 6379
      password:

db:
    medical:
        url: jdbc:mysql://172.30.1.251:3306/medical?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&queryInterceptors=com.bben.medical.common.LogSqlQueryInterceptor
        username: root
        password: 123456

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
